import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/components/fonts";

export const metadata: Metadata = {
  title: "McHenry Educational Consultancy",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
